export const COLLECTIONS = {
    user: 'User',
}

export const NEW = "new";
export const EMPTY = "empty";
export const VALID = "valid";
export const INVALID = "invalid";
export const NONE = "none";
export const DUPLICATE = "duplicate";
export const FIND = "find";
export const FIND_ONE = "findOne";
export const DELETE = "delete";
export const DELETE_ONE = "deleteOne";
export const INSERT_ONE = "insertOne";
export const INSERT_MANY = "insertMany";
export const UPDATE_MANY = "updateMany";
export const AGGREGATE = "aggregate";
export const PROPAGATE = "propagate";
export const UPDATE_ONE = "updateOne";
export const INITIATE_BULK_UPD = "initiateBulkUpdate";
export const TESTING_HALINA = "testing_halina";
export const TESTING_HALINA_REFERENCE = "testing_halina_reference";
export const IMTI_V_95 = "imti_test_v0.95";
export const IMTI_V_95_PRISTINE = "imti_test_v0.95-pristine";
export const GLOB_TEST_WITH_EXC = "global_and_local_updates_testing_with_exclusions";
export const GLOB_TEST_WITH_EXC_FOR_APP = "global_and_local_updates_testing_with_exclusions_for_app";
export const TEST_FX_FEE_0_2 = "test_fx_fees_0.2";
export const TEST_FX_FEE_0_3 = "test_fx_fees_0.3";
export const FX_FEES_0_2 = "FxFeesTest-v0.2-reference";
export const FX_FEES_0_2_PRISTINE = "FxFeesTest-v0.2-reference-pristine";
export const FX_FEES_0_3 = "FxFeesTest-v0.3-reference";
export const CONFIGURATION = "configurations";
export const USER_CUSTOM_CONFIGURATIONS = "UserCustomConfigurations";
export const WB_COLLECTION_TRACKING_FOR_TESTING = "wb_collection_tracking_for_testing";
export const USER = "User";
export const FX_FEES_WB_TESTING = "FxFeesWB_testing";
export const FX_FEES_WB_REFERENCE = "FxFeesWB_reference";
export const WB_COLLECTION_TRACKING_EXTERNAL_TESTING = "wb_collection_tracking_external_testing";
export const WB_COLLECTION_TRACKING = "wb_collection_tracking";
export const WB_COLLECTION_TRACKING_REFERENCE = "wb_collection_tracking_reference";

export class DBFields {
    static AREA_KM_2 = "area_km2";
    static POPULATION = "population";
    static GDP_GROWTH = "gdp_growth";
    static RECORD_ID = "RecordId";
    static CONSUMER_MARGINS = "ConsumerMargins";
    static VALID = "valid";
    static TYPE = "type";
    static DATE_TYPE = "date";
    static IMAGE_LINKS = "ImageLinks";
    static CURRENT_STATE = "CurrentState";
    static AUDIT_SESSIONS = "AuditSessions";
    static AUDIT_VALUE_ARRAY = "AuditValueArray";
    static AUDIT_FIELD_NAME = "AuditFieldName";
    static NEW_VALUE = "NewValue";
    static OLD_VALUE = "OldValue";
    static AUDITED_COMMENT = "AuditedComment";
    static ENUM = "enumerate";
    static BOOL = "bool";
    static GTE = "gte";
    static LTE = "lte";
    static GT = "gt";
    static LT = "lt";
    static LT_NOW = "lt_now";
    static COMMENT = "comment";
    static AMOUNTS_AND_RATES = "amounts_and_rates";
    static DATETIME_COLLECTED_UTC = "datetime_collected_utc";
    static UTC = "utc";
    static INTERBANK_RATE = "interbank_rate";
    static RESEARCHER_NAME = "ResearcherName";
    static FULL_COST = "full_cost";
    static FX_MARGIN = "fx_margin";
    static COLLECTION_TABLE = "collection_table";
}
