FROM node:12
WORKDIR /app
COPY . /app
ENV DISABLE_ESLINT_PLUGIN=true
RUN npm install && npm install pm2 yarn -g && npm rebuild node-sass
RUN npm install serve -g
RUN npm run build
ENTRYPOINT serve -s build -l 3000
EXPOSE 3000
