version: '2'
services:
  chrome:
    image: selenium/node-chrome:4.0.0-alpha-7-prerelease-20201009
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  firefox:
    image: selenium/node-firefox:4.0.0-alpha-7-prerelease-20201009
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6901:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-alpha-7-prerelease-20201009
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4445:4444"
    environment:
      - GRID_BROWSER_TIMEOUT=20000
      - GRID_TIMEOUT=10000
  pytests:
    container_name: selenium_pytests
    command: /bin/sleep infinity
    build: .
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ./.:/opt/app/