const GET_DATA_BY_FIRMID = 'GET_DATA_BY_FIRMID';
const GET_CONFIG = 'GET_CONFIG';
const SET_DATA = 'SET_DATA';
const SET_CONFIG = 'SET_CONFIG';
const SET_CONFIG_LIST = 'SET_CONFIG_LIST';
const SAVE_DATA = 'SAVE_DATA';

const AUTH_REGISTER = 'AUTH_REGISTER';
const AUTH_SET_REGISTERD_USER = 'AUTH_SET_REGISTERD_USER';

const AUTH_LOGIN = 'AUTH_LOGIN';
const ADD_SEARCH_FIELD = 'ADD_SEARCH_FIELD';
const DELETE_FIELD = 'DELETE_FIELD';
const GET_CONFIGS = 'GET_CONFIGS';

const COPY_RECORD = 'COPY_RECORD';
const ADD_RECORD = 'ADD_RECORD';
const GET_RECORD = 'GET_RECORD';
const UPLOAD_FILE = 'UPLOAD_FILE';
const SET_FILE = 'SET_FILE';
const REMOVE_FILE = 'REMOVE_FILE';
const SET_CHART_DATA = 'SET_CHART_DATA';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export {  //eslint-disable-line
  GET_DATA_BY_FIRMID,
  SET_DATA,
  GET_CONFIG,
  SET_CONFIG,
  SAVE_DATA,
  SET_CHART_DATA,

  AUTH_REGISTER,
  AUTH_SET_REGISTERD_USER,
  AUTH_LOGIN,
  ADD_SEARCH_FIELD,
  DELETE_FIELD,
  COPY_RECORD,
  GET_CONFIGS,
  SET_CONFIG_LIST,
  GET_RECORD,
  UPLOAD_FILE,
  SET_FILE,
  ADD_RECORD,
  REMOVE_FILE,
  CHANGE_PASSWORD,
};
